%%% This file was automatically generated by snmpc_mib_to_hrl version 5.2.5
%%% Date: 18-Mar-2017::13:31:46
-ifndef('LLDP-MIB').
-define('LLDP-MIB', true).

%% Notifications
-define(lldpRemTablesChange, [1,0,8802,1,1,2,0,0,1]).

%% Oids

-define(lldpMIB, [1,0,8802,1,1,2]).

-define(lldpNotifications, [1,0,8802,1,1,2,0]).

-define(lldpNotificationPrefix, [1,0,8802,1,1,2,0,0]).

-define(lldpObjects, [1,0,8802,1,1,2,1]).

-define(lldpConfiguration, [1,0,8802,1,1,2,1,1]).
-define(lldpMessageTxInterval, [1,0,8802,1,1,2,1,1,1]).
-define(lldpMessageTxInterval_instance, [1,0,8802,1,1,2,1,1,1,0]).
-define(lldpMessageTxHoldMultiplier, [1,0,8802,1,1,2,1,1,2]).
-define(lldpMessageTxHoldMultiplier_instance, [1,0,8802,1,1,2,1,1,2,0]).
-define(lldpReinitDelay, [1,0,8802,1,1,2,1,1,3]).
-define(lldpReinitDelay_instance, [1,0,8802,1,1,2,1,1,3,0]).
-define(lldpTxDelay, [1,0,8802,1,1,2,1,1,4]).
-define(lldpTxDelay_instance, [1,0,8802,1,1,2,1,1,4,0]).
-define(lldpNotificationInterval, [1,0,8802,1,1,2,1,1,5]).
-define(lldpNotificationInterval_instance, [1,0,8802,1,1,2,1,1,5,0]).

-define(lldpPortConfigTable, [1,0,8802,1,1,2,1,1,6]).

-define(lldpPortConfigEntry, [1,0,8802,1,1,2,1,1,6,1]).
-define(lldpPortConfigPortNum, 1).
-define(lldpPortConfigAdminStatus, 2).
-define(lldpPortConfigNotificationEnable, 3).
-define(lldpPortConfigTLVsTxEnable, 4).

-define(lldpConfigManAddrTable, [1,0,8802,1,1,2,1,1,7]).

-define(lldpConfigManAddrEntry, [1,0,8802,1,1,2,1,1,7,1]).
-define(lldpConfigManAddrPortsTxEnable, 1).

-define(lldpStatistics, [1,0,8802,1,1,2,1,2]).
-define(lldpStatsRemTablesLastChangeTime, [1,0,8802,1,1,2,1,2,1]).
-define(lldpStatsRemTablesLastChangeTime_instance, [1,0,8802,1,1,2,1,2,1,0]).
-define(lldpStatsRemTablesInserts, [1,0,8802,1,1,2,1,2,2]).
-define(lldpStatsRemTablesInserts_instance, [1,0,8802,1,1,2,1,2,2,0]).
-define(lldpStatsRemTablesDeletes, [1,0,8802,1,1,2,1,2,3]).
-define(lldpStatsRemTablesDeletes_instance, [1,0,8802,1,1,2,1,2,3,0]).
-define(lldpStatsRemTablesDrops, [1,0,8802,1,1,2,1,2,4]).
-define(lldpStatsRemTablesDrops_instance, [1,0,8802,1,1,2,1,2,4,0]).
-define(lldpStatsRemTablesAgeouts, [1,0,8802,1,1,2,1,2,5]).
-define(lldpStatsRemTablesAgeouts_instance, [1,0,8802,1,1,2,1,2,5,0]).

-define(lldpStatsTxPortTable, [1,0,8802,1,1,2,1,2,6]).

-define(lldpStatsTxPortEntry, [1,0,8802,1,1,2,1,2,6,1]).
-define(lldpStatsTxPortNum, 1).
-define(lldpStatsTxPortFramesTotal, 2).

-define(lldpStatsRxPortTable, [1,0,8802,1,1,2,1,2,7]).

-define(lldpStatsRxPortEntry, [1,0,8802,1,1,2,1,2,7,1]).
-define(lldpStatsRxPortNum, 1).
-define(lldpStatsRxPortFramesDiscardedTotal, 2).
-define(lldpStatsRxPortFramesErrors, 3).
-define(lldpStatsRxPortFramesTotal, 4).
-define(lldpStatsRxPortTLVsDiscardedTotal, 5).
-define(lldpStatsRxPortTLVsUnrecognizedTotal, 6).
-define(lldpStatsRxPortAgeoutsTotal, 7).

-define(lldpLocalSystemData, [1,0,8802,1,1,2,1,3]).
-define(lldpLocChassisIdSubtype, [1,0,8802,1,1,2,1,3,1]).
-define(lldpLocChassisIdSubtype_instance, [1,0,8802,1,1,2,1,3,1,0]).
-define(lldpLocChassisId, [1,0,8802,1,1,2,1,3,2]).
-define(lldpLocChassisId_instance, [1,0,8802,1,1,2,1,3,2,0]).
-define(lldpLocSysName, [1,0,8802,1,1,2,1,3,3]).
-define(lldpLocSysName_instance, [1,0,8802,1,1,2,1,3,3,0]).
-define(lldpLocSysDesc, [1,0,8802,1,1,2,1,3,4]).
-define(lldpLocSysDesc_instance, [1,0,8802,1,1,2,1,3,4,0]).
-define(lldpLocSysCapSupported, [1,0,8802,1,1,2,1,3,5]).
-define(lldpLocSysCapSupported_instance, [1,0,8802,1,1,2,1,3,5,0]).
-define(lldpLocSysCapEnabled, [1,0,8802,1,1,2,1,3,6]).
-define(lldpLocSysCapEnabled_instance, [1,0,8802,1,1,2,1,3,6,0]).

-define(lldpLocPortTable, [1,0,8802,1,1,2,1,3,7]).

-define(lldpLocPortEntry, [1,0,8802,1,1,2,1,3,7,1]).
-define(lldpLocPortNum, 1).
-define(lldpLocPortIdSubtype, 2).
-define(lldpLocPortId, 3).
-define(lldpLocPortDesc, 4).

-define(lldpLocManAddrTable, [1,0,8802,1,1,2,1,3,8]).

-define(lldpLocManAddrEntry, [1,0,8802,1,1,2,1,3,8,1]).
-define(lldpLocManAddrSubtype, 1).
-define(lldpLocManAddr, 2).
-define(lldpLocManAddrLen, 3).
-define(lldpLocManAddrIfSubtype, 4).
-define(lldpLocManAddrIfId, 5).
-define(lldpLocManAddrOID, 6).

-define(lldpRemoteSystemsData, [1,0,8802,1,1,2,1,4]).

-define(lldpRemTable, [1,0,8802,1,1,2,1,4,1]).

-define(lldpRemEntry, [1,0,8802,1,1,2,1,4,1,1]).
-define(lldpRemTimeMark, 1).
-define(lldpRemLocalPortNum, 2).
-define(lldpRemIndex, 3).
-define(lldpRemChassisIdSubtype, 4).
-define(lldpRemChassisId, 5).
-define(lldpRemPortIdSubtype, 6).
-define(lldpRemPortId, 7).
-define(lldpRemPortDesc, 8).
-define(lldpRemSysName, 9).
-define(lldpRemSysDesc, 10).
-define(lldpRemSysCapSupported, 11).
-define(lldpRemSysCapEnabled, 12).

-define(lldpRemManAddrTable, [1,0,8802,1,1,2,1,4,2]).

-define(lldpRemManAddrEntry, [1,0,8802,1,1,2,1,4,2,1]).
-define(lldpRemManAddrSubtype, 1).
-define(lldpRemManAddr, 2).
-define(lldpRemManAddrIfSubtype, 3).
-define(lldpRemManAddrIfId, 4).
-define(lldpRemManAddrOID, 5).

-define(lldpRemUnknownTLVTable, [1,0,8802,1,1,2,1,4,3]).

-define(lldpRemUnknownTLVEntry, [1,0,8802,1,1,2,1,4,3,1]).
-define(lldpRemUnknownTLVType, 1).
-define(lldpRemUnknownTLVInfo, 2).

-define(lldpRemOrgDefInfoTable, [1,0,8802,1,1,2,1,4,4]).

-define(lldpRemOrgDefInfoEntry, [1,0,8802,1,1,2,1,4,4,1]).
-define(lldpRemOrgDefInfoOUI, 1).
-define(lldpRemOrgDefInfoSubtype, 2).
-define(lldpRemOrgDefInfoIndex, 3).
-define(lldpRemOrgDefInfo, 4).

-define(lldpExtensions, [1,0,8802,1,1,2,1,5]).

-define(lldpConformance, [1,0,8802,1,1,2,2]).

-define(lldpCompliances, [1,0,8802,1,1,2,2,1]).

-define(lldpGroups, [1,0,8802,1,1,2,2,2]).

-define(lldpConfigGroup, [1,0,8802,1,1,2,2,2,1]).

-define(lldpConfigRxGroup, [1,0,8802,1,1,2,2,2,2]).

-define(lldpConfigTxGroup, [1,0,8802,1,1,2,2,2,3]).

-define(lldpStatsRxGroup, [1,0,8802,1,1,2,2,2,4]).

-define(lldpStatsTxGroup, [1,0,8802,1,1,2,2,2,5]).

-define(lldpLocSysGroup, [1,0,8802,1,1,2,2,2,6]).

-define(lldpRemSysGroup, [1,0,8802,1,1,2,2,2,7]).

-define(lldpNotificationsGroup, [1,0,8802,1,1,2,2,2,8]).


%% Range values
-define(low_lldpMessageTxInterval, 5).
-define(high_lldpMessageTxInterval, 32768).
-define(low_lldpMessageTxHoldMultiplier, 2).
-define(high_lldpMessageTxHoldMultiplier, 10).
-define(low_lldpReinitDelay, 1).
-define(high_lldpReinitDelay, 10).
-define(low_lldpTxDelay, 1).
-define(high_lldpTxDelay, 8192).
-define(low_lldpNotificationInterval, 5).
-define(high_lldpNotificationInterval, 3600).
-define(low_lldpPortConfigPortNum, 1).
-define(high_lldpPortConfigPortNum, 4096).
-define(low_lldpConfigManAddrPortsTxEnable, 0).
-define(high_lldpConfigManAddrPortsTxEnable, 512).
-define(low_lldpStatsRemTablesInserts, 0).
-define(high_lldpStatsRemTablesInserts, 4294967295).
-define(low_lldpStatsRemTablesDeletes, 0).
-define(high_lldpStatsRemTablesDeletes, 4294967295).
-define(low_lldpStatsRemTablesDrops, 0).
-define(high_lldpStatsRemTablesDrops, 4294967295).
-define(low_lldpStatsRemTablesAgeouts, 0).
-define(high_lldpStatsRemTablesAgeouts, 4294967295).
-define(low_lldpStatsTxPortNum, 1).
-define(high_lldpStatsTxPortNum, 4096).
-define(low_lldpStatsTxPortFramesTotal, 0).
-define(high_lldpStatsTxPortFramesTotal, 4294967295).
-define(low_lldpStatsRxPortNum, 1).
-define(high_lldpStatsRxPortNum, 4096).
-define(low_lldpStatsRxPortFramesDiscardedTotal, 0).
-define(high_lldpStatsRxPortFramesDiscardedTotal, 4294967295).
-define(low_lldpStatsRxPortFramesErrors, 0).
-define(high_lldpStatsRxPortFramesErrors, 4294967295).
-define(low_lldpStatsRxPortFramesTotal, 0).
-define(high_lldpStatsRxPortFramesTotal, 4294967295).
-define(low_lldpStatsRxPortTLVsDiscardedTotal, 0).
-define(high_lldpStatsRxPortTLVsDiscardedTotal, 4294967295).
-define(low_lldpStatsRxPortTLVsUnrecognizedTotal, 0).
-define(high_lldpStatsRxPortTLVsUnrecognizedTotal, 4294967295).
-define(low_lldpStatsRxPortAgeoutsTotal, 0).
-define(high_lldpStatsRxPortAgeoutsTotal, 4294967295).
-define(low_lldpLocChassisId, 1).
-define(high_lldpLocChassisId, 255).
-define(low_lldpLocSysName, 0).
-define(high_lldpLocSysName, 255).
-define(low_lldpLocSysDesc, 0).
-define(high_lldpLocSysDesc, 255).
-define(low_lldpLocPortNum, 1).
-define(high_lldpLocPortNum, 4096).
-define(low_lldpLocPortId, 1).
-define(high_lldpLocPortId, 255).
-define(low_lldpLocPortDesc, 0).
-define(high_lldpLocPortDesc, 255).
-define(low_lldpLocManAddr, 1).
-define(high_lldpLocManAddr, 31).
-define(low_lldpLocManAddrLen, -2147483648).
-define(high_lldpLocManAddrLen, 2147483647).
-define(low_lldpLocManAddrIfId, -2147483648).
-define(high_lldpLocManAddrIfId, 2147483647).
-define(low_lldpRemLocalPortNum, 1).
-define(high_lldpRemLocalPortNum, 4096).
-define(low_lldpRemIndex, 1).
-define(high_lldpRemIndex, 2147483647).
-define(low_lldpRemChassisId, 1).
-define(high_lldpRemChassisId, 255).
-define(low_lldpRemPortId, 1).
-define(high_lldpRemPortId, 255).
-define(low_lldpRemPortDesc, 0).
-define(high_lldpRemPortDesc, 255).
-define(low_lldpRemSysName, 0).
-define(high_lldpRemSysName, 255).
-define(low_lldpRemSysDesc, 0).
-define(high_lldpRemSysDesc, 255).
-define(low_lldpRemManAddr, 1).
-define(high_lldpRemManAddr, 31).
-define(low_lldpRemManAddrIfId, -2147483648).
-define(high_lldpRemManAddrIfId, 2147483647).
-define(low_lldpRemUnknownTLVType, 9).
-define(high_lldpRemUnknownTLVType, 126).
-define(low_lldpRemUnknownTLVInfo, 0).
-define(high_lldpRemUnknownTLVInfo, 511).
-define(low_lldpRemOrgDefInfoOUI, 3).
-define(high_lldpRemOrgDefInfoOUI, 3).
-define(low_lldpRemOrgDefInfoSubtype, 1).
-define(high_lldpRemOrgDefInfoSubtype, 255).
-define(low_lldpRemOrgDefInfoIndex, 1).
-define(high_lldpRemOrgDefInfoIndex, 2147483647).
-define(low_lldpRemOrgDefInfo, 0).
-define(high_lldpRemOrgDefInfo, 507).


%% Definitions from 'LldpManAddrIfSubtype'
-define('LldpManAddrIfSubtype_systemPortNumber', 3).
-define('LldpManAddrIfSubtype_ifIndex', 2).
-define('LldpManAddrIfSubtype_unknown', 1).

%% Definitions from 'LldpPortIdSubtype'
-define('LldpPortIdSubtype_local', 7).
-define('LldpPortIdSubtype_agentCircuitId', 6).
-define('LldpPortIdSubtype_interfaceName', 5).
-define('LldpPortIdSubtype_networkAddress', 4).
-define('LldpPortIdSubtype_macAddress', 3).
-define('LldpPortIdSubtype_portComponent', 2).
-define('LldpPortIdSubtype_interfaceAlias', 1).

%% Definitions from 'LldpChassisIdSubtype'
-define('LldpChassisIdSubtype_local', 7).
-define('LldpChassisIdSubtype_interfaceName', 6).
-define('LldpChassisIdSubtype_networkAddress', 5).
-define('LldpChassisIdSubtype_macAddress', 4).
-define('LldpChassisIdSubtype_portComponent', 3).
-define('LldpChassisIdSubtype_interfaceAlias', 2).
-define('LldpChassisIdSubtype_chassisComponent', 1).

%% Enum definitions from lldpPortConfigAdminStatus
-define(lldpPortConfigAdminStatus_disabled, 4).
-define(lldpPortConfigAdminStatus_txAndRx, 3).
-define(lldpPortConfigAdminStatus_rxOnly, 2).
-define(lldpPortConfigAdminStatus_txOnly, 1).

%% Enum definitions from lldpPortConfigNotificationEnable
-define(lldpPortConfigNotificationEnable_false, 2).
-define(lldpPortConfigNotificationEnable_true, 1).

%% Enum definitions from lldpLocManAddrSubtype
-define(lldpLocManAddrSubtype_reserved, 65535).
-define(lldpLocManAddrSubtype_gwid, 24).
-define(lldpLocManAddrSubtype_fibreChannelWWNN, 23).
-define(lldpLocManAddrSubtype_fibreChannelWWPN, 22).
-define(lldpLocManAddrSubtype_xtpNativeModeXTP, 21).
-define(lldpLocManAddrSubtype_xtpOverIpv6, 20).
-define(lldpLocManAddrSubtype_xtpOverIpv4, 19).
-define(lldpLocManAddrSubtype_asNumber, 18).
-define(lldpLocManAddrSubtype_distinguishedName, 17).
-define(lldpLocManAddrSubtype_dns, 16).
-define(lldpLocManAddrSubtype_e164withNsap, 15).
-define(lldpLocManAddrSubtype_banyanVines, 14).
-define(lldpLocManAddrSubtype_decnetIV, 13).
-define(lldpLocManAddrSubtype_appleTalk, 12).
-define(lldpLocManAddrSubtype_ipx, 11).
-define(lldpLocManAddrSubtype_x121, 10).
-define(lldpLocManAddrSubtype_f69, 9).
-define(lldpLocManAddrSubtype_e164, 8).
-define(lldpLocManAddrSubtype_e163, 7).
-define(lldpLocManAddrSubtype_all802, 6).
-define(lldpLocManAddrSubtype_bbn1822, 5).
-define(lldpLocManAddrSubtype_hdlc, 4).
-define(lldpLocManAddrSubtype_nsap, 3).
-define(lldpLocManAddrSubtype_ipV6, 2).
-define(lldpLocManAddrSubtype_ipV4, 1).
-define(lldpLocManAddrSubtype_other, 0).

%% Enum definitions from lldpRemManAddrSubtype
-define(lldpRemManAddrSubtype_reserved, 65535).
-define(lldpRemManAddrSubtype_gwid, 24).
-define(lldpRemManAddrSubtype_fibreChannelWWNN, 23).
-define(lldpRemManAddrSubtype_fibreChannelWWPN, 22).
-define(lldpRemManAddrSubtype_xtpNativeModeXTP, 21).
-define(lldpRemManAddrSubtype_xtpOverIpv6, 20).
-define(lldpRemManAddrSubtype_xtpOverIpv4, 19).
-define(lldpRemManAddrSubtype_asNumber, 18).
-define(lldpRemManAddrSubtype_distinguishedName, 17).
-define(lldpRemManAddrSubtype_dns, 16).
-define(lldpRemManAddrSubtype_e164withNsap, 15).
-define(lldpRemManAddrSubtype_banyanVines, 14).
-define(lldpRemManAddrSubtype_decnetIV, 13).
-define(lldpRemManAddrSubtype_appleTalk, 12).
-define(lldpRemManAddrSubtype_ipx, 11).
-define(lldpRemManAddrSubtype_x121, 10).
-define(lldpRemManAddrSubtype_f69, 9).
-define(lldpRemManAddrSubtype_e164, 8).
-define(lldpRemManAddrSubtype_e163, 7).
-define(lldpRemManAddrSubtype_all802, 6).
-define(lldpRemManAddrSubtype_bbn1822, 5).
-define(lldpRemManAddrSubtype_hdlc, 4).
-define(lldpRemManAddrSubtype_nsap, 3).
-define(lldpRemManAddrSubtype_ipV6, 2).
-define(lldpRemManAddrSubtype_ipV4, 1).
-define(lldpRemManAddrSubtype_other, 0).

%% Default values
-define(default_lldpMessageTxInterval, 30).
-define(default_lldpMessageTxHoldMultiplier, 4).
-define(default_lldpReinitDelay, 2).
-define(default_lldpTxDelay, 2).
-define(default_lldpNotificationInterval, 5).
-define(default_lldpPortConfigAdminStatus, 3).
-define(default_lldpPortConfigNotificationEnable, 2).
-define(default_lldpPortConfigTLVsTxEnable, 0).
-define(default_lldpConfigManAddrPortsTxEnable, []).
-define(default_lldpStatsRemTablesLastChangeTime, 0).
-define(default_lldpStatsRemTablesInserts, 0).
-define(default_lldpStatsRemTablesDeletes, 0).
-define(default_lldpStatsRemTablesDrops, 0).
-define(default_lldpStatsRemTablesAgeouts, 0).
-define(default_lldpLocChassisIdSubtype, 1).
-define(default_lldpLocChassisId, []).
-define(default_lldpLocSysName, []).
-define(default_lldpLocSysDesc, []).
-define(default_lldpLocSysCapSupported, 0).
-define(default_lldpLocSysCapEnabled, 0).

-endif.
